# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Featured Map"
  description:
  icon: explore
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    display_social_media_links: true
    heading:
    content:
    list_items: ["bookshop:generic/labelled-icon"]
    map: "bookshop:simple/google-map-embed"
    button: "TODO"
  styles:
    background_variant: Light

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

_inputs:
  content:
    content:
    type: html