# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left/Right block"
  description: Left/Right content block
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  data:
    heading: bookshop:generic/component-heading
    content: 
    buttons:
      - label:
    icons: [bookshop:generic/labelled-icon]
  styles:
    orientation:
    image:


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  content:
    type: markdown