# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Video"
  description: "Simple video component"
  icon: ondemand_videogit
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  video_source:
  video_url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  video_source: "YouTube"
  video_url: https://www.youtube.com/watch?v=LeqKIzeZel4

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  video_source: 
    - "Youtube"
    - "Vimeo"
