# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Icon Card Grid"
  description:
  icon: table_chart
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    eyebrow_headline:
    heading:
    text:
    grid_items:
      - icon:
        eyebrow_headline:
        primary_heading:
        text:
        button:
          label: Secondary
          url:
          open_in_new_tab: false
    buttons: [bookshop:generic/button]
  styles:
    background_variant: Dark

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
