source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    hidden: true
  eleventyExcludeFromCollections:
    hidden: true
  draft:
    type: switch
  value:
    comment: Write the name of any font from https://fonts.google.com/ to allow it to be selected in data/site for the site fonts
_select_data: {}
_structures:
  content_blocks:
    style: select
    id_key: _bookshop_name
    values:
      - value:
          _bookshop_name: generic/sample
          text:
        label: Sample
        description:
        icon:
        tags: []
        _inputs: {}
_editables: {}
data_config:
  fonts: true
timezone: Etc/UTC
