source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    hidden: true
  eleventyExcludeFromCollections:
    hidden: true
  draft:
    type: switch
_select_data: {}
_structures:
  content_blocks:
    style: select
    id_key: _bookshop_name
    values:
      - value:
          _bookshop_name: generic/sample
          text:
        label: Sample
        description:
        icon:
        tags: []
        _inputs: {}
_editables:
  content:
    bold: true
    format: p h1 h2 h3 h4 
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: false
    embed: true 
    horizontalrule: true
    image: true
    table: false
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    snippet: false

data_config: {}
timezone: Etc/UTC
