# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Contact block"
  description: Contact content block
  icon: contact_phone
  tags: ['contact', 'content-block', 'left-right']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    social_icons: true
    heading: 
      bookshop: generic/component-heading
      primary_heading: A contact block
      eyebrow_headline: ''
    description: This is a simple yet powerful block to display not only your location by using Google Maps, but also any other contact details you wish to share with your customers.
    contact_details:
      - text: mybusiness@business.com
        hero_icon_name: envelope
    button: bookshop:generic/button!    
  styles:
    orientation: Left
    background_variant: dark


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    social_icons: true
    heading:
      bookshop: generic/component-heading
      primary_heading: A contact block
      eyebrow_headline: ''
    content: Content
    contact_details:
      - text: mybusiness@business.com
        hero_icon_name: envelope
    button: bookshop:generic/button    
  styles:
    orientation: Left
    background_variant: dark

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  heading:
    eyebrow_headline: ''
  description:
    type: textarea  

_structures:
  content.contact_details:
    - label: Email
      value:
        text: mybusiness@business.com
        hero_icon_name: envelope
    - label: Custom
      value:
        text: ''
        hero_icon_name: ''