# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Contact block"
  description: Contact content block
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    social_media_links: 
      - link_url: #
        svg_icon: bookshop:generic/icon
    heading: bookshop:generic/component-heading
    description: 
    contact_details: [bookshop:generic/labelled-icon]
    button: bookshop:generic/button    
  styles:
    orientation:
    background_variant: light


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  data:
    heading:
      bookshop: generic/component-heading
      primary_heading: A contact block
    content: Content
    button:
    icons:
      - bookshop: generic/labelled-icon
        arrangement: inline
        text: Icon text
        icon: bookshop:generic/icon
  styles:
    orientation: Left
    background_variant: dark

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea