# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Text Block"
  description: Block of content with a header
  icon: article
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading!
    text: There are many reasons a website should have a terms of use agreement. For example, a terms of use page would show the website is a legitimate operation and increase user confidence. However, the most important reasons a business should have a terms and conditions page are to limit the business's liability, prevent users from abusing the service, protect the site's intellectual property, and ensure that the users comply with the site's terms.
  styles:
    background_variant: light

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
