# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Checkbox Group"
  description: Group of checkbox inputs
  icon: check_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  checkboxes: [bookshop:generic/form/checkbox-input]
  arrangement: inline
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Checkbox group
  checkboxes: 
    - bookshop:generic/form/checkbox-input
    - bookshop:generic/form/checkbox-input
    - bookshop:generic/form/checkbox-input

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helper_text:
    comment: Helpful text for the user such as 'Do not select more than 2'
  id:
    hidden: true
    instance_value: UUID
