# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Select Input"
  description: A select input with custom options
  icon: create
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name_and_id: ""
  label: ""
  options:
    - key:
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Select input
  name_and_id: option-selector
  options:
    - key: Option 1
    - key: Option 2
    - key: Option 3
    - key: Option 4

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name_and_id:
    comment: Provides a unique identifier for the input
  helper_text:
    comment: Helpful text for the user such as 'Option 1 is only available on weekends'
