# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Social Icons"
  description: Icon links to social media platforms
  icon: diversity_3
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  social_media_links:
    - link_url: https://www.youtube.com/
      svg_icon: /assets/images/icons/social/youtube.svg
    - link_url: https://www.facebook.com/
      svg_icon: /assets/images/icons/social/facebook.svg
    - link_url: https://www.linkedin.com/
      svg_icon: /assets/images/icons/social/linkedin.svg
    - link_url: https://www.twitter.com/
      svg_icon: /assets/images/icons/social/x.svg
    - link_url: https://www.instagram.com/
      svg_icon: /assets/images/icons/social/instagram.svg
  style:
    icon_hover_color: "#f9f9fb"
    icon_fill_color: "#f9f9fb"
    icon_fill_color_hover: "#000000"

   

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  social_media_links:
    - link_url: https://www.youtube.com/
      svg_icon: /assets/images/icons/social/youtube.svg
    - link_url: https://www.facebook.com/
      svg_icon: /assets/images/icons/social/facebook.svg
    - link_url: https://www.linkedin.com/
      svg_icon: /assets/images/icons/social/linkedin.svg
    - link_url: https://www.twitter.com/
      svg_icon: /assets/images/icons/social/x.svg
    - link_url: https://www.instagram.com/
      svg_icon: /assets/images/icons/social/instagram.svg
  style:
    icon_hover_color: "#f9f9fb"
    icon_fill_color: "#f9f9fb"
    icon_fill_color_hover: "#000000"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  social_media_links:
    type: array
    options:
      structures:
        values:
          - label: Social Media Link
            icon: link
            value:
              link_url:
              svg_icon:
          _inputs:
            svg_icon:
              type: image
  svg_icon:
    type: image
  icon_fill_color:
    type: color 
  icon_hover_color:
    type: color
  icon_fill_color_hover:
    type: color
