# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Form Builder"
  description: Build a form with the developed inputs
  icon: dynamic_form
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id: 
  form_submission_type: email/cloudcannon
  success_page: ""
  inputs: [bookshop:structure:form_blocks]
  tandc_checkbox: bookshop:generic/form/checkbox-input
  submit_button: bookshop:generic/form/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  id: 727a56cc-0bfc-4ab4-901e-144f407cd1ae
  inputs:
    - _bookshop_name: generic/form/text-input
      label: Full name
      placeholder: John Smith
      id: full_name
      required: true
      helper_text: You do not need to include any middle names
    - _bookshop_name: generic/form/email-input
      id: email
      label: Email
      required: false
      placeholder: mybusiness@smallbusiness.com
      helper_text: Your personal email
    - _bookshop_name: generic/form/phone-input
      label: Phone number
      placeholder: +64 21 859292
      id: phone_number
      required: false
      helper_text: Your personal phone number
    - _bookshop_name: generic/form/radio-button-group
      label: Radio Button group
      required: true
      radio_buttons:
        - label: Radio button 1
          checked: false
        - label: Radio button 2
          checked: true
        - label: Radio button 3
          checked: false
        - label: Radio button 4
          checked: false
      arrangement: inline
      helper_text: Radio button 1 is only available on weekends
    - _bookshop_name: generic/form/checkbox-group
      label: Checkbox group
      checkboxes:
        - _bookshop_name: generic/form/checkbox-input
          group_name:
          label: Checkbox
          checked: false
          required: false
          id: 0cd76c37-3678-4b71-b676-061de9061eca
        - _bookshop_name: generic/form/checkbox-input
          group_name:
          label: Checkbox
          checked: true
          required: false
          id: b73cc3d9-a34d-43dc-b9ce-40c8b9670583
        - _bookshop_name: generic/form/checkbox-input
          group_name:
          label: Checkbox
          checked: false
          required: false
          id: 7c97077e-b0eb-42ba-8e6e-3da627e1684e
      arrangement: inline
      helper_text: Do not select more than 2
    - _bookshop_name: generic/form/country-select-input
      id: country-selector
      label: Country
      required: false
      placeholder: Select your country
      helper_text: The country you primarily reside in
    - _bookshop_name: generic/form/date-input
      id: date
      label: Choose a date
      required: false
      min: "2023-11-03"
      max: null
      helper_text: The date cannot be in the past
    - _bookshop_name: generic/form/time-input
      label: Choose a time slot
      placeholder: '15:00'
      id: time
      required: false
      min: '09:00'
      max: '17:00'
      helper_text: Select a time between 9:00 and 15:00
    - _bookshop_name: generic/form/select-input
      id: option-selector
      label: Select
      options:
        - key: Option 1
        - key: Option 2
        - key: Option 3
        - key: Option 4
      required: false
      helper_text: Option 1 is only available on weekdays
    - _bookshop_name: generic/form/text-area-input
      label: Comment
      placeholder: Any helpful information we should know about
      id: comment
      rows: 2
      required: false
      helper_text: Let us know things such as if you have any allergies
    - _bookshop_name: generic/form/checkbox-group
      label: Terms and conditions
      checkboxes:
        - _bookshop_name: generic/form/checkbox-input
          group_name:
          label: Do you accept the terms and conditions?
          checked: false
          required: true
          id: beff4820-604b-4d23-a74b-47625baa2c3f
      arrangement: inline
      helper_text: You can view the terms and conditions at /terms-and-conditions

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  form_submission_type:
    comment: This option will provide the type of submission that will be targeted. 
    type: select
    options:
      values:
      - email/cloudcannon
      - mailchimp
  id:
    hidden: true
    instance_value: UUID
  success_page:
    type: url
    comment:  The page to redirect to after submission (mailchimp something like https://company.us12.list-manage.com/subscribe?u=c2asfj8ec0sdfjsadlfe3f&id=88786d434e)