# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Checkbox Input"
  description: A single checkbox input
  icon: check_box
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  id:
  label: ""
  checked: false
  required: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Checkbox"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    hidden: true
    comment: This input should be hidden from editors and passed through from the radio-group component so that these inputs function correctly