# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Text Block"
  description: Block of content with a header
  icon: article
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/component-heading!
  content: bookshop:generic/text-block!

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
