# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Custom Icon"
  description: A icon (that you upload) with an optional border and customisable color
  icon: bolt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icon_path: 
  icon_size: small
  icon_type: solid
  rounded_border: false
  color: "#f9f9fb"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  icon_path: /assets/images/icons/social/youtube.svg

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color:
    comment: This controls the icon color (if the icon is an svg) and the rounded border color (if one is included)
  icon_size:
    type: choice
    options:
      values:
        - small
        - large
  icon_type:
    type: choice
    options:
      values:
        - solid
        - outline
  icon_path:
    type: image