# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Rich Text Editor"
  description:
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: >-
    Until now, trying to style an article, document, or blog post with Tailwind has been a tedious task that required a keen eye for typography and a lot of complex custom CSS.

    By default, Tailwind removes all of the default browser styling from paragraphs, headings, lists and more. This ends up being really useful for building application UIs because you spend less time undoing user-agent styles, but when you&nbsp;*really are*&nbsp;just trying to style some content that came from a rich-text editor in a CMS or a markdown file, it can be surprising and unintuitive.

    We get lots of complaints about it actually, with people regularly asking us things like:

    > Why is Tailwind removing the default styles on my h1 elements? How do I disable this? What do you mean I lose all the other base styles too?

    We hear you, but we're not convinced that simply disabling our base styles is what you really want. You don't want to have to remove annoying margins every time you use a p&nbsp;element in a piece of your dashboard UI. And I doubt you really want your blog posts to use the user-agent styles either — you want them to look&nbsp;*awesome*, not awful.

    The @tailwindcss/typography plugin is our attempt to give you what you&nbsp;*actually*&nbsp;want, without any of the downsides of doing something stupid like disabling our base styles.

    It adds a new prose class that you can slap on any block of vanilla HTML content and turn it into a beautiful, well-formatted document:

    &lt;article class="prose"&gt; &lt;h1&gt;Garlic bread with cheese: What the science tells us&lt;/h1&gt; &lt;p&gt; For years parents have espoused the health benefits of eating garlic bread with cheese to their children, with the food earning such an iconic status in our culture that kids will often dress up as warm, cheesy loaf for Halloween. &lt;/p&gt; &lt;p&gt; But a recent study shows that the celebrated appetizer may be linked to a series of rabies cases springing up around the country. &lt;/p&gt; &lt;!-- ... --&gt; &lt;/article&gt;

    For more information about how to use the plugin and the features it includes,&nbsp;[read the documentation](https://github.com/tailwindcss/typography/blob/master/README.md).

    ## What to expect from here on out

    What follows from here is just a bunch of absolute nonsense I've written to dogfood the plugin itself. It includes every sensible typographic element I could think of, like&nbsp;**bold text**, unordered lists, ordered lists, code blocks, block quotes,&nbsp;*and even italics*.

    It's important to cover all of these use cases for a few reasons:

    1. We want everything to look good out of the box.
    2. Really just the first reason, that's the whole point of the plugin.
    3. Here's a third pretend reason though a list with three items looks more realistic than a list with two items.

    Now we're going to try out another header style.

    ### Typography should be easy

    So that's a header for you — with any luck if we've done our job correctly that will look pretty reasonable.

    Something a wise person once told me about typography is:

    > Typography is pretty important if you don't want your stuff to look like trash. Make it good then it won't be bad.

    It's probably important that images look okay here by default as well:
          
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
