# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Form"
  description:
  icon: dynamic_form
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading!
    description: Description text to compliment the block
    form: bookshop:simple/form-builder
  styles:
    background_variant: light
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea
  content_alignment:
    type: choice
    options:
      value_key: id
      preview:
        text: 
          - key: name
        icon:
          - key: icon
      values:
        - name: Left
          id: left
          icon: format_align_left
        - name: Center
          id: center
          icon: format_align_center
  background_variant:
    type: choice
    options:
      value_key: id
      preview:
        text: 
          - key: name
        icon:
          - key: icon
      values:
        - name: Dark
          id: dark
          icon: dark_mode
        - name: Light
          id: light
          icon: light_mode