# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image-card"
  description: Block that contain image and description
  icon: perm_media
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  is_image: false
  image: 
  icon: bookshop:generic/icon
  heading: bookshop:generic/component-heading
  content: bookshop:generic/text-block
  link_url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
