# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Time-input"
  description: Time selection input
  icon: alarm
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  placeholder: ""
  name_and_id: ""
  helper_text:
  min:
  max:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Choose a time slot
  name_and_id: time
  placeholder: 15:00
  min: 09:00
  max: 17:00

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name_and_id:
    comment: Provides a unique identifier for the input
  helper_text:
    comment: Helpful text for the user such as 'Pick a time between 9:00 and 17:00'
