# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Card Grid"
  description:
  icon: table_chart
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading
    description:
    grid_items:
      - hero_icon_name:
        eyebrow_headline:
        primary_heading:
        text:
        button:
          label: Secondary
          url:
          open_in_new_tab: false
    buttons: [bookshop:generic/button]
  styles:
    background_variant: secondary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/component-heading
      eyebrow_headline: Eyebrow Heading
      primary_heading: Primary Heading
    description: Card Grid Description
    grid_items:
      - image: http://placekitten.com/g/200/300
        hero_icon_name: adjustments-horizontal
        eyebrow_headline: Eyebrow Heading
        primary_heading: Primary Heading
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        button:
          label: Secondary
          url: /
          open_in_new_tab: false
      - image: http://placekitten.com/g/200/300
        hero_icon_name: adjustments-horizontal
        eyebrow_headline: Eyebrow Heading
        primary_heading: Primary Heading
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        button:
          label: Secondary
          url: /
          open_in_new_tab: false
      - image: http://placekitten.com/g/200/300
        hero_icon_name: adjustments-horizontal
        eyebrow_headline: Eyebrow Heading
        primary_heading: Primary Heading
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
        button:
          label: Secondary
          url: /
          open_in_new_tab: false
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: Button text
        variant: primary
        arrow: right
  styles:
    background_variant: secondary
# Any extra CloudCannon inputs configuration to apply to the blueprint
