# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Featured icons"
  description: Represents key features or services in a nice iconed layout
  icon: dataset
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    headline:
    heading:
    icon:
    buttons: [bookshop:generic/button]
  styles:
    orientation: Left
    image: bookshop:generic/image
    background_variant: Dark


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    headline: Let your features shine
    heading: A featured icons left right block
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: "Book Now"
        variant: "primary"
        disabled: false
        arrow: "right"
        onclick: 
  styles:
    orientation: Left
    background_variant: Dark
    image: 
      bookshop: generic/image
      image_path: https://placekitten.com/300/500
      image_alt: A cute kitten


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon_path:
    type: image
  icon:
    type: array
    options:
      structures:
        values:
          - label: custom-icon
            icon_path: 
          - label: icon
            hero_icon_name: arrow-right
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  background_variant:
    type: select
    options:
      values:
        - 'Dark'
        - 'Light'