# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Radio Button Group"
  description: Group of radio button inputs
  icon: radio_button_unchecked
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  radio_buttons: [bookshop:generic/form/radio-input]
  arrangement: inline
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Radio Button group"
  radio_buttons:
    - _bookshop_name: generic/form/radio-input
      label: Radio button 1
      id: radio-button-1
    - _bookshop_name: generic/form/radio-input
      label: Radio button 2
      id: radio-button-2
    - _bookshop_name: generic/form/radio-input
      label: Radio button 3
      id: radio-button-3
    - _bookshop_name: generic/form/radio-input
      label: Radio button 4
      id: radio-button-4

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  arrangement:
    type: select
    comment: The layout of the icon and text together
    options:
      values:
        - inline
        - stacked
  helper_text:
    comment: Helpful text for the user such as 'Option 1 is only available on weekends'