# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Radio Input"
  description: A single radio button input to be used in a radiobutton group
  icon: radio_button_unchecked
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  checked: false
  required: false
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Radio button"
  id: radio-button

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    hidden: true
    comment: This input should be hidden from editors and passed through from the radio-group component so that these inputs function correctly
