# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Date Input"
  description: Calendar date picker input
  icon: date_range
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  required: false
  min_today: true
  min:
  max_today:
  max:
  helper_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Choose a date

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    hidden: true
    instance_value: UUID
  helper_text:
    comment: Helpful text for the user such as 'The date should be after today'
  min:
    hidden: min_today
    type: date
  max:
    hidden: max_today
    type: date
  min_today:
    type: switch
    comment: On if the minimum date to be selected should always be the current date
  max_today:
    type: switch
    comment: On if the maximum date to be selected should always be the current date