# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Grid - Icon Cards"
  description: "Create a grid of cards displaying an icon, text content and a button"
  icon: table_chart
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/heading!
    description:
    grid_items:
      - hero_icon_name:
        heading: bookshop:generic/heading!
        text:
        button: bookshop:generic/button!
    buttons: [bookshop:generic/button]
  styles:
    background_variant: secondary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading: bookshop:generic/heading
    description: Card Grid Description
    grid_items:
      - hero_icon_name: adjustments-horizontal
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
      - hero_icon_name: adjustments-horizontal
        eyebrow_headline: Eyebrow Heading
        primary_heading: Primary Heading
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
      - hero_icon_name: adjustments-horizontal
        text: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
          ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat.
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: Button text
        variant: primary
        arrow: right
  styles:
    background_variant: secondary
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea
