# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Card"
  description: A card that contains an image/icon and description
  icon: perm_media
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  headings: bookshop:generic/component-heading
  details: These versatile cards can be used to talk about your services or products, or anything else you are keen to share with your audience. They come with an action link to get your users into the journey you’ve crafted for them.
  link_label: Book Now
  link_url:
  icon: bookshop:generic/icon
  image: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  headings: 
    _bookshop_name: generic/component-heading
    eyebrow_headline: SIMPLE CARD
    primary_heading: PRIMARY HEADING
  details: >- 
    versatile cards can be used to talk about your services or products, or anything else you are keen to share with your audience. They come with an action link to get your users into the journey you’ve crafted for them.
  link_label: Book Now
  link_url:
  icon:
    _bookshop_name: generic/icon
    svg_icon: puzzle-piece
    icon_size: small
    icon_type: solid
    rounded_border: false
    color: '#111111'
  image: 

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
