# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Component-heading"
  description: Header text for your content
  icon: view_headline
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  eyebrow_headline: Eyebrow Heading
  primary_heading: Primary Heading


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  eyebrow_headline: EYEBROW HEADLINE
  primary_heading: A simple text block

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: