# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left/Right block"
  description: Content that can be arranged left-right or right-left
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading
    content: 
    buttons: [bookshop:generic/button]
    icons: [bookshop:generic/labelled-icon]
  styles:
    orientation:
    image: bookshop:generic/image
    background_variant: "Dark"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      bookshop: generic/component-heading
      eyebrow_headline: Let your features shine
      primary_heading: A featured icons left right block
    content: Content
    buttons:
      url: "#"
      open_in_new_tab: false
      text: "Button text"
      variant: "primary"
      disabled: false
      arrow: "right"
      onclick: 
    icons:
      - bookshop: generic/labelled-icon
        arrangement: inline
        text: Icon text
        icon:
          bookshop: generic/icon
          hero_icon_name: academic-cap
          icon_size: small
          rounded_border: true
          icon_type: solid
  styles:
    orientation: Left
    background_variant: "Dark"
    image: 
      bookshop: generic/image
      image_path: /assets/images/Left-Right--featured-image.png
      image_alt: A woman laughing


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  content:
    type: markdown
  background_variant:
    type: select
    options:
      values:
        - 'Dark'
        - 'Light'