# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Left/Right block"
  description: Content that can be arranged left-right or right-left
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    social_icons: bookshop:generic/social-icons 
    heading: bookshop:generic/component-heading
    contact_details:
    author_name:
    buttons: [bookshop:generic/button]
    icons: [bookshop:generic/labelled-icon]
  styles:
    orientation:
    image: bookshop:generic/image
    background_variant: "Dark"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    social_icons:
      bookshop: generic/social-icons
      social_media_links:
        - link_url: https://www.youtube.com/
          svg_icon: /assets/images/icons/social/youtube.svg
    heading:
      bookshop: generic/component-heading
      eyebrow_headline: Let your features shine
      primary_heading: A featured icons left right block
    contact_details: >-
      This is a simple yet powerful block to display not only your location by using Google Maps, but also any other contact details you wish to share with your customers.
    author_name: John Smith
    buttons:
      url: "#"
      open_in_new_tab: false
      text: "Button text"
      variant: "primary"
      disabled: false
      arrow: "right"
      onclick: 
    icons:
      - bookshop: generic/labelled-icon
        arrangement: inline
        text: Icon text
        icon:
          bookshop: generic/icon
          hero_icon_name: academic-cap
          icon_size: small
          rounded_border: true
          icon_type: solid
  styles:
    orientation: Left
    background_variant: "Dark"
    image: 
      bookshop: generic/image
      image_path: https://placekitten.com/300/500
      image_alt: A cute kitten


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  contact_details:
    type: markdown
  background_variant:
    type: select
    options:
      values:
        - 'Dark'
        - 'Light'