# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  url: "#"
  text: "Hello World!"
  variant: "secondary"
  disabled: true
  arrow: "up"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  url: "#"
  text: "Hello World!"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
